sudo: required
services:
  - docker

before_install:
  - docker build -t sarik123/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sarik123/docker-react npm run test -- --coverage

#by In a single container application where there is a Dockerfile in the root of the project,
#EBS will look for it and use it automatically to build the container.
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-893848630104"
  bucket-path: "docker-react"
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"